# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-25 04:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='date Created')),
                ('page_name', models.CharField(max_length=64)),
                ('line_number', models.CharField(max_length=5)),
                ('working_on', models.CharField(max_length=255)),
                ('goals', models.CharField(max_length=255)),
            ],
        ),
    ]
